name: Feature request
description: Something fsearch should do
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What would you like?
      description: The workflow you're trying to achieve, not just the mechanism.
    validations:
      required: true
